api_platform:
    title: 'rDig (next)'
    description: 'rDig *dig reloaded. Archaeological contexts and findings structured archive'
    version: '0.0.1'
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    resource_class_directories:
        - '%kernel.project_dir%/src/Entity'
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
