language: php

os: linux

dist: bionic

services:
    - mysql

before_script:
    - mysql < tests/common/su.sql

php:
    - "7.2"
    - "7.3"
cache:
    directories:
         - $HOME/.composer/cache/files
         - $HOME/symfony-bridge/.phpunit
before_install:
    - echo "memory_limit=2G" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
    - if [[ $COVERAGE != true ]]; then phpenv config-rm xdebug.ini || true; fi
    - if ! [ -z "$STABILITY" ]; then composer config minimum-stability ${STABILITY}; fi;
    - if ! [ -v "$DEPENDENCIES" ]; then composer require --no-update ${DEPENDENCIES}; fi;
install:
    - COMPOSER_MEMORY_LIMIT=-1 composer update ${COMPOSER_FLAGS} --prefer-dist --no-interaction
script:
    - bin/phpunit -v $PHPUNIT_FLAGS

